### ISSUE TITLE
Adding a 6th HPDL1414 Module

### ISSUE THREAD

**Issue by ComputerZOO** [RoelandR/HPDL-1414-board#1]
Hello Roeland,
I am struggling a little bit. How can I add a 6th Display-Module by using GPB7 on the MCP23017 (labeled extra2 in your schematic) to display 24 characters?

**Comment by RoelandR** [comment]
Hello Max,

It is possible to use extra2 to add a 6th display. The program I wrote only supports 5 display modules. You can add a sixth module by extending the position table with 4 more position codes. In this postable the active DS1 - DS6 module bit should be set to 0. (bits 7 6 5 4 3 2 are the DS select bits) The first position of the most left module is 7B -> 0111.1011 I see that I ignored the possibility to use bit 7 for DS6. So that bit must be set to 1 for all current positions. Otherwise DS6 wil be selected always. The new posTable[] must be: (not tested by me) int PosTable[] = {0xfb, 0xfa, 0xf9, 0xf8, 0xf7, 0xf6, 0xf5, 0xf4, 0xef, 0xee, 0xed, 0xec, 0xdf, 0xde, 0xdd, 0xdc, 0xbf, 0xbe, 0xbd, 0xbc, 0x7f, 0x7e, 0x7d, 0x7c};
The current pcb should still work correctly with this PosTable. When that is oke you have to modify the program so it supports all 24 characters. Please let me know if it works. I am not able to test this at the moment. 
kind regards, Roeland Riemens.
